
export const projectsData = [
  {
    id: 11,
    title: "Taste-Enhancing AR/VR:",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar1.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar3.png?raw=true",
  ],
    category: ["ml & ai","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Leveraged Unity and ARuCo tags to create an immersive app altering food's visual appeal. Bachelor's thesis highlighting how enticing visuals can elevate taste perception.",
    tags:["C#","VR","AR"],
    features:["Augment Food","Real-Time Application","Calibration & Testing"],
    codeURL: "https://github.com/ToniRajamaki/FoodAugmentationWithUnity",
    demoURL: "https://www.youtube.com/watch?v=sUQpsuETWJc&ab_channel=ToniRajam%C3%A4ki"
  },
  {
    id: 10,
    title: "Image Recognition",
    images: ["https://github.com/ToniRajamaki/folio2/blob/abf8282d6520d05917c332c64b8e702e58a94076/public/assets/projects/cifar10/cifar2.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cifar10/cifar1.jpg?raw=true"],
    category: ["ml & ai","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Python-based image recognition app delving into Cifar-10 dataset. Explored classifiers' impact on results, yielding captivating insights and an enjoyable project journey.",
    tags:["Python","Keras","TensorFlow"],
    features:["Trains With Data","Multiple Classifier Methods","Bayesian","Performance analysis"],
    codeURL: "https://github.com/ToniRajamaki/Machine-Learning",
  },
  {
    id: 13,
    title: "Modular React Creations",
    images: [
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez1.png?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez2.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez3.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez4.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez5.gif?raw=true",
    ],
    category: ["web","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Collection of React apps/components with meticulous state design, prioritizing reusability. A joyful endeavor, demonstrating the power of well-structured, modular development.",
    tags:["JavaScript","React","Redux"],
    features:["Lots Of Tiny Projects","Careful State Design","API","Axios"],
    codeURL: "https://github.com/ToniRajamaki?tab=repositories&q=&type=&language=javascript&sort=",
  },
  {
    id: 1,
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/portfolio2.png?raw=true"],
    title: "Portfolio Project",
    category: ["web","featured"],
    description:"This is one my latest works, a highly interactive personal website that multitude of features. Designed with care, it has unobtrusive animations that lend a hint of charm to the browsing experience. As you navigate the simple layout, I hope you find something of interest.",
    tags:["JavaScript","React","UI/UX"],
    features:["Asymptotic Efficiecny","Optimized","Adaptive Algorithms"],
    codeURL:"https://github.com/ToniRajamaki/folio2",
    demoURL:"https://tonirajamaki.github.io/folio2/"
  },
  {
    id: 2,
    title: "Tetris++",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/tetris.png?raw=true"],
    category: ["other","featured"],
    video: "/assets/camping.mp4",
    description: "C++ Tetris rebirth via Qt Creator's GUI editor. Infused with creativity, this project offered both a playful twist on the classic game and a humorous dance with GUI complexities",
    tags:["C++","Qtcreator"],
    features:["Tetris with twist","Keep Track of hiscore","Adjust the difficulty"],
    codeURL: "https://github.com/ToniRajamaki/tetris-",
  },
  {
    id: 3,
    title: "FUZU 3D Mobile Game",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu2.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu3.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu4.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu5.jpg?raw=true",
  ],
  category: ["app","featured"],
  video: "/assets/CloneYoutube.mkv",
  description: "Major 3D project at G3, starring 'Fuzu' the bird. Navigate obstacles, acquire XP and Eggs for advancement. Unveil a world of optimized performance and captivating gameplay.",
  tags:["C#","Unity","G3"],
  features:["3D Platformer","Beautiful lvl Design","Skill tree","Highly Optimized"],
  demoURL:"https://www.youtube.com/watch?v=bjdl9BJKhxI&ab_channel=GitGudGames"
},
  {
    id: 4,
    title: "Pirkanmaa Domination",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/pirkanmaan_valloitus.png?raw=true"],
    category: ["other"],
    video: "/assets/gym.mp4",
    description: "Dive into this resource-driven territory simulator. Outmaneuver your opponent, tactically manage resources, explore 'Pate's deals', and race to construct the decisive nuclear plant for victory.",
    tags:["C++","Pair Programming"],
    features:["Multiplayer","Random-Gen map","5 Unique resources"],
    codeURL:"https://github.com/ToniRajamaki/dominationGame/tree/main",
  },

  {
    id: 6,
    title: "Cyberpunk: Rogue Turret",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber5.png?raw=true",
  ],
  category: ["app","featured"],
    video: "/assets/todo.mp4",
    description: "Crafted at G3, a high-performance, visually stunning roguelike turret game. Engage waves of foes, upgrade with innovative enhancements, and wield new weaponry.",
    tags:["C#","Unity","G3"],
    features:["Highly Optimized","Fully Randomized","Stunning Visuals","40% D1 Retention"],
    demoURL:"https://www.youtube.com/watch?v=mQf923EoPJE&ab_channel=GitGudGames"
  },

  {
    id: 7,
    title: "Juice Master",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice0.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice4.png?raw=true",
  ],
  category: ["app","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "A G3 project where players dives into crafting diverse juices, balancing complexity and delight. Navigate traps, ensuring your creations remain pristine. The juice business awaits your strategic finesse.",
    tags:["C#","Unity","G3"],
    features:["Create Luxurious Drinks","Cool Animated processes","Make money with your drinks"],
    demoURL:"https://play.google.com/store/apps/details?id=com.gitgudgames.juicemaker"
  },
  {
    id: 8,
    title: "Tampere Bus Algorithms",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/bus.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/bus2.png?raw=true"],
    category: ["other"],
    video: "/assets/gym_mobile.mp4",
    description: "Optimized Data Handling using unordered_maps selected for efficient handling of frequent functions achieving O(N) insertion, removal, and Θ(1) search. used vectors for less critical tasks due to their user-friendly nature.",
    tags:["C++","Optimization"],
    features:["Asymptotic Efficiecny","Optimized","Adaptive Algorithms"],
    codeURL:"https://github.com/ToniRajamaki/TIRAGA_bus_stops"
  },
 
  
  {
    id: 12,
    title: "Ninja Blog",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog0.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog1.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog2.gif?raw=true,"],
    category: ["web","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Unveiling my first React project, a dynamic blog hub. Immerse in ninja sagas, contribute your narratives. Crafted under YouTube's expert guidance for a stepping stone into web development.",
    tags:["JavaScript","React","Axios"],
    features:["Write Blogs","Create and Store New ones","Minimalistic Design"],
    codeURL:"https://github.com/ToniRajamaki/Ninja-react-blog"
  },
  {
    id: 5,
    title: "Suez Unblocker",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez1.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez2.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez3.png?raw=true"],
    category: ["app"],
    video: "/assets/movie.mp4",
    description: "G3's quick gem spun from Suez Canal saga. Simple clicker game with depth. Witness random animations, NPC camaraderie, and vibrant sounds for an immersive adventure.",
    tags:["C#","Unity","G3"],
    features:["Clicker Game","Trending","Immersive Audio design"],
    demoURL:"https://play.google.com/store/apps/details?id=com.GitGudGamesOy.FreeSuezCanal"
  },
  //############# UI/UX PROJECTS ###############
  {
    id: 14,
    title: "FitAR",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/5.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/6.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/4.gif?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 15,
    title: "FutuMED",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 16,
    title: "Habitica ReDesign",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/6.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/Rectangle 1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/Rectangle 2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 3.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 17,
    title: "SAMPO",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/9.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 18,
    title: "LibreOffice Settings",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 20,
    title: "TOAS Heuristic evaluation",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/9.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 19,
    title: "Feedback Engagement",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/thumbnail.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/5.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 21,
    title: "TALK HOME",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/10.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/3.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://drive.google.com/drive/folders/1IW9FSVE8lchmszNK4VcD8oQVYco8UkJv?usp=sharing"
  },
  {
    id: 22,
    title: "FitnessBPM",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/thumbnail.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/9.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/5.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/vM5s9GExMRFpzVYZAuMsd7/Innovation-course-WIreframes?page-id=0%3A1&type=design&node-id=1-4&viewport=547%2C-77%2C0.94&t=jsuyFro2DdxFAzsL-1&scaling=scale-down&starting-point-node-id=1%3A96&mode=design"
  },

];

export const projectsNav = [
  {
    name: "featured",
  },
  {
    name: "Web",
  },
  {
    name: "app",
  },
  {
    name: "ML & AI",
  },
  {
    name: "other",
  },
  {
    name: 'UI/UX',
  },
  {
    name: "all",
  }
];

