
export const projectsData = [
  {
    id: 11,
    title: "Taste-Enhancing AR/VR:",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar1.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ar/ar3.png?raw=true",
  ],
    category: ["other","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Leveraged Unity and ARuCo tags to create an immersive app altering food's visual appeal. Bachelor's thesis highlighting how enticing visuals can elevate taste perception.",
    tags:["C#","VR","AR"],
    features:["Augment Food","Real-Time Application","Calibration & Testing"],
    codeURL: "https://github.com/ToniRajamaki/FoodAugmentationWithUnity",
    demoURL: "https://www.youtube.com/watch?v=sUQpsuETWJc&ab_channel=ToniRajam%C3%A4ki"
  },
  {
    id: 10,
    title: "Image Recognition",
    images: ["https://github.com/ToniRajamaki/folio2/blob/abf8282d6520d05917c332c64b8e702e58a94076/public/assets/projects/cifar10/cifar2.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cifar10/cifar1.jpg?raw=true"],
    category: ["other","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Python-based image recognition app delving into Cifar-10 dataset. Explored classifiers' impact on results, yielding captivating insights and an enjoyable project journey.",
    tags:["Python","Keras","TensorFlow"],
    features:["Trains With Data","Multiple Classifier Methods","Bayesian","Performance analysis"],
    codeURL: "https://github.com/ToniRajamaki/Machine-Learning",
  },
  {
    id: 13,
    title: "Modular React Creations",
    images: [
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez1.png?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez2.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez3.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez4.gif?raw=true",
      "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/mini_projects/ez5.gif?raw=true",
    ],
    category: ["web","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Collection of React apps/components with meticulous state design, prioritizing reusability. A joyful endeavor, demonstrating the power of well-structured, modular development.",
    tags:["JavaScript","React","Redux"],
    features:["Lots Of Tiny Projects","Careful State Design","API","Axios"],
    codeURL: "https://github.com/ToniRajamaki?tab=repositories&q=&type=&language=javascript&sort=",
  },
  {
    id: 1,
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/portfolio2.png?raw=true"],
    title: "Portfolio Project",
    category: ["web","featured"],
    description:"This is one my latest works, a highly interactive personal website that multitude of features. Designed with care, it has unobtrusive animations that lend a hint of charm to the browsing experience. As you navigate the simple layout, I hope you find something of interest.",
    tags:["JavaScript","React","UI/UX"],
    features:["Asymptotic Efficiecny","Optimized","Adaptive Algorithms"],
    codeURL:"https://github.com/ToniRajamaki/folio2",
    demoURL:"https://tonirajamaki.github.io/folio2/"
  },
  {
    id: 2,
    title: "Tetris++",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/tetris.png?raw=true"],
    category: ["other","featured"],
    video: "/assets/camping.mp4",
    description: "C++ Tetris rebirth via Qt Creator's GUI editor. Infused with creativity, this project offered both a playful twist on the classic game and a humorous dance with GUI complexities",
    tags:["C++","Qtcreator"],
    features:["Tetris with twist","Keep Track of hiscore","Adjust the difficulty"],
    codeURL: "https://github.com/ToniRajamaki/tetris-",
  },
  {
    id: 3,
    title: "FUZU 3D Mobile Game",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu2.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu3.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu4.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/fuzu/fuzu5.jpg?raw=true",
  ],
  category: ["app","featured"],
  video: "/assets/CloneYoutube.mkv",
  description: "Major 3D project at G3, starring 'Fuzu' the bird. Navigate obstacles, acquire XP and Eggs for advancement. Unveil a world of optimized performance and captivating gameplay.",
  tags:["C#","Unity","G3"],
  features:["3D Platformer","Beautiful lvl Design","Skill tree","Highly Optimized"],
  demoURL:"https://www.youtube.com/watch?v=bjdl9BJKhxI&ab_channel=GitGudGames"
},
  {
    id: 4,
    title: "Pirkanmaa Domination",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/pirkanmaan_valloitus.png?raw=true"],
    category: ["other"],
    video: "/assets/gym.mp4",
    description: "Dive into this resource-driven territory simulator. Outmaneuver your opponent, tactically manage resources, explore 'Pate's deals', and race to construct the decisive nuclear plant for victory.",
    tags:["C++","Pair Programming"],
    features:["Multiplayer","Random-Gen map","5 Unique resources"],
    codeURL:"https://github.com/ToniRajamaki/dominationGame/tree/main",
  },

  {
    id: 6,
    title: "Cyberpunk: Rogue Turret",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/cyberpunk/cyber5.png?raw=true",
  ],
  category: ["app","featured"],
    video: "/assets/todo.mp4",
    description: "Crafted at G3, a high-performance, visually stunning roguelike turret game. Engage waves of foes, upgrade with innovative enhancements, and wield new weaponry.",
    tags:["C#","Unity","G3"],
    features:["Highly Optimized","Fully Randomized","Stunning Visuals","40% D1 Retention"],
    demoURL:"https://www.youtube.com/watch?v=mQf923EoPJE&ab_channel=GitGudGames"
  },

  {
    id: 7,
    title: "Juice Master",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice0.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/juice/juice4.png?raw=true",
  ],
  category: ["app","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "A G3 project where players dives into crafting diverse juices, balancing complexity and delight. Navigate traps, ensuring your creations remain pristine. The juice business awaits your strategic finesse.",
    tags:["C#","Unity","G3"],
    features:["Create Luxurious Drinks","Cool Animated processes","Make money with your drinks"],
    demoURL:"https://play.google.com/store/apps/details?id=com.gitgudgames.juicemaker"
  },
  {
    id: 8,
    title: "Tampere Bus Algorithms",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/bus.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/misc/bus2.png?raw=true"],
    category: ["other"],
    video: "/assets/gym_mobile.mp4",
    description: "Optimized Data Handling using unordered_maps selected for efficient handling of frequent functions achieving O(N) insertion, removal, and Θ(1) search. used vectors for less critical tasks due to their user-friendly nature.",
    tags:["C++","Optimization"],
    features:["Asymptotic Efficiecny","Optimized","Adaptive Algorithms"],
    codeURL:"https://github.com/ToniRajamaki/TIRAGA_bus_stops"
  },
 
  
  {
    id: 12,
    title: "Ninja Blog",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog0.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog1.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/ninja_blog/blog2.gif?raw=true,"],
    category: ["web","featured"],
    video: "/assets/gym_mobile.mp4",
    description: "Unveiling my first React project, a dynamic blog hub. Immerse in ninja sagas, contribute your narratives. Crafted under YouTube's expert guidance for a stepping stone into web development.",
    tags:["JavaScript","React","Axios"],
    features:["Write Blogs","Create and Store New ones","Minimalistic Design"],
    codeURL:"https://github.com/ToniRajamaki/Ninja-react-blog"
  },
  {
    id: 5,
    title: "Suez Unblocker",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez1.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez2.png?raw=true","https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/suez/suez3.png?raw=true"],
    category: ["app"],
    video: "/assets/movie.mp4",
    description: "G3's quick gem spun from Suez Canal saga. Simple clicker game with depth. Witness random animations, NPC camaraderie, and vibrant sounds for an immersive adventure.",
    tags:["C#","Unity","G3"],
    features:["Clicker Game","Trending","Immersive Audio design"],
    demoURL:"https://play.google.com/store/apps/details?id=com.GitGudGamesOy.FreeSuezCanal"
  },
  //############# UI/UX PROJECTS ###############
  {
    id: 14,
    title: "FitAR",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/thumbnail.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/5.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/6.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/fitar/4.gif?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FITAR is a smartphone app that uses Augmented Reality (AR) to help gym-goers understand exercises better. It offers customizable workout plans, letting users easily pick exercises for each session. This makes planning workouts simple. The app shows a life-sized virtual humanoid demonstrating exercises right on your phone screen. Users can watch these exercises from various angles in real-time. This feature helps in maintaining proper form and preventing injuries. It's like having a personal trainer available 24/7 through AR. Additionally, users can rate the exercises and workout plans, providing valuable feedback and personalizing their fitness journey.",
    tags:["AR","UI/UX","Product Design","Interaction Design"],
    features:["Augmented Reality","Promote healthy lifestyle","Personal trainer"],
    demoURL:"https://www.figma.com/proto/QL1J9OfPg9Qmh8QPwGBZYy/HTI-560-FITAR?page-id=0%3A1&node-id=1-3&starting-point-node-id=1%3A3&mode=design&t=FVgUIZZd3DHnatnN-1"
  },
  {
    id: 15,
    title: "FutuMED",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/thumbnail.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/medical/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our UI/UX project FutuMED, we focused on creating a tool that revolutionizes healthcare by enabling remote and automated monitoring of vital signs. This concept, inspired by team member Kati's insights as a nurse, aims to ease the daily routines of medical professionals. FutuMED integrates digitization and artificial intelligence to display comprehensive data on patients' lifestyles, physical, and mental health. Adhering to rigorous standards like the EU General Data Protection Regulation, it promises to enhance patient care, improve diagnostics, and ensure safety. This project showcases a forward-thinking approach in healthcare technology, emphasizing efficiency and personalized patient care",
    tags:["Human-centered Design","User research","UX Evaluation"],
    features:["Vital tracking","Remote Monitoring","Patient profiles"],
    demoURL:""
  },
  {
    id: 16,
    title: "Habitica ReDesign",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/thumbnail.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/Rectangle 1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/Rectangle 2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/habitica_redesign/image 3.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our UI/UX project, we innovated upon the existing Habitica app, a tool for habit and productivity management. Our approach involved brainstorming new ideas to enhance user motivation, building upon the app's existing framework. We got inspired by Duolingos way of being able to set up wager for goal and thus implemnted such system. We focused on creating interactive designs using Figma, which allowed us to visualize our enhancements in a tangible way. These designs aimed to deepen user engagement by integrating elements of self-determination and goal-setting theories, transforming routine tasks into imaginative quests and incorporating progression features like experience bars and levels. We also enhanced the social aspect of the app by designing more interactive parties, fostering community and peer support. Our process included rigorous testing of these designs to ensure they effectively resonated with users, ultimately aiming to elevate the overall user experience in Habitica.",
    tags:["UX Design","Wireframing","Product Development"],
    features:["Reward system","Task Customization","Positive reinforcement"],
    demoURL:""
  },
  {
    id: 17,
    title: "SAMPO",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/9.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sampo/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "A 3 person-project, Sampo, is a web service designed to boost study motivation and encourage physical activity among young people. Its core value proposition is offering an enjoyable way to achieve personal goals alongside friends. A key focus of Sampo is enhancing community spirit within educational institutions and fostering networking among students. The service features student registration by organizations, allowing them to join specific subject communities or class groups. This enables students to freely create their own groups, compete, or organize random events with other groups. Activities range from sports competitions like kyykkä to academic challenges, such as accumulating the most study credits in a year. While primarily aimed at secondary education students, Sampo is open to external participants, broadening its community reach and impact.",
    tags:["UI/UX Design","Interactive Design","Responsive","Service Design"],
    features:["Promoting Study motivation","Event Organazing","Community goals & hiscores"],
    demoURL:"https://www.figma.com/proto/NDfItwans8AxX29clPr0u9/HTI-2-Esiteht%C3%A4v%C3%A4-4-wf?node-id=25-1061&starting-point-node-id=25%3A1061&mode=design&t=VNNUXv6wLGFu5riv-1"
  },
  {
    id: 18,
    title: "LibreOffice Settings",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/thumbnail2.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/libreoffice/2.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our five-person project, we collaborated with one of the creators of LibreOffice to redesign its options dialog, aiming to enhance user accessibility and simplify its interface. The original design of LibreOffice, a product of The Document Foundation, was feature-rich but overwhelming for novice users. Our challenge was to balance the needs of different user groups, maintaining functionality while removing clutter. Through user research, including analyzing bug reports and conducting interviews, we identified key areas for improvement. We created an affinity diagram to pinpoint issues in the complex menu and developed a prototype in Figma. Our design emphasized usability, and we worked closely with The Document Foundation using their resources, like a whiteboard, for effective categorization. In the end, the LibreOffice creator was pleased with our work, acknowledging our contribution to making the software more accessible and user-friendly. This collaboration highlighted the importance of user-centered design in open-source software development.",
    tags:["OpenSource project","UX/UI","User Research","Usability Testing"],
    features:["Enhanced accessibility","User-Friendly Navigation","Intuitive Design"],
    demoURL:""
  },
  {
    id: 20,
    title: "TOAS Heuristic evaluation",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/thumbnail.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/toas/4.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our five-member team project, we conducted a usability assessment of the TOAS housing foundation's website, focusing on the perspective of under-25-year-old housing applicants. We carried out the evaluation remotely via Zoom, involving four participants—three on computers and one on a mobile device. Each test session was led by a moderator responsible for task distribution and communication, while two observers silently monitored the proceedings. Our assessment covered 11 tasks related to site navigation, information retrieval, property management, and application form completion, all relevant to a student’s housing search. We identified 22 usability issues, rated on a severity scale from 1 (critical) to 4 (cosmetic), with most problems being significant or minor usability issues. Despite testers initially having a good impression of the site, it was ultimately perceived as somewhat illogical and cumbersome. The housing foundation, TOAS, was very pleased with the thoroughness and insights of our work, rewarding our efforts with movie tickets, a gesture that highlighted their appreciation of our contribution to improving their website's user experience.",
    tags:["Heuristic Evaluation","Usability Testing","UX  Testing"],
    features:["User-centric approach","Extensive heuristic evaluation","Usability Tested"],
    demoURL:""
  },
  {
    id: 19,
    title: "Feedback Engagement",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/thumbnail.gif?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/feedback/5.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our four-person team, we collaborated on a fun and experience-driven project to design an engaging feedback system for restaurants. We observed that many restaurants don't actively collect on-site feedback, and customers often hesitate to voice concerns directly. To address this, we proposed an online feedback system embedded in the restaurant's website, enabling honest post-meal reviews. Our design counters the aggressive tactics seen in current systems, like persistent pop-ups on delivery sites, which can discourage genuine feedback. We also considered the lack of incentives in existing systems; a complicated or unrewarding process might lead to less thoughtful responses. By simplifying the feedback process and integrating it seamlessly into the restaurant's existing online presence, we aimed to make the system beneficial for both customers and restaurants. This approach would encourage honest feedback, making customers feel their opinions are valued and helping restaurants improve their service and offerings.",
    tags:["Experience Driven Design","UI/UX","Interaction Design"],
    features:["Responsive Design","User-friendly interface","Minimalistic & Seamless"],
    demoURL:"https://www.figma.com/proto/vgWK2iVmD49yt4I1e3ycYY/Feedback-system-low-fi-ptototype-design?page-id=0%3A1&node-id=2-2&starting-point-node-id=2%3A2&t=NU0coJ3XJq3U5Qzw-1&mode=design"
  },
  {
    id: 21,
    title: "TALK HOME",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/thumbnail.jpg?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/5.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/6.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/home_assistant/3.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "In our four-person team, we developed a futuristic smart voice assistant, focusing on enhancing the interaction with smart home devices. This project, rooted in extensive background research, involved expanding on existing speech command technologies while infusing substantial user customization options. Our approach was inspired by current solutions, but we aimed to introduce innovative concepts and features that cater to future needs. Central to our design was the improvement of user experience, especially for those with mobility impairments, achieved through natural language processing and intuitive controls. This assistant not only offered hands-free convenience for busy individuals but also integrated seamlessly with other smart home technologies. Our efforts culminated in creating a more accessible, efficient, and user-friendly smart home environment, demonstrating our commitment to pushing the boundaries of auditory interaction in smart technology.",
    tags:["UI/UX","Product Design","Human-Centered Design"],
    features:["Speech Command Recognition","Highly customizable","Home automation"],
    demoURL:"https://drive.google.com/drive/folders/1IW9FSVE8lchmszNK4VcD8oQVYco8UkJv?usp=sharing"
  },
  {
    id: 22,
    title: "FitnessBPM",
    images: ["https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/thumbnail2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/1.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/2.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/7.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/8.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/9.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/3.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/4.png?raw=true",
    "https://github.com/ToniRajamaki/folio2/blob/main/public/assets/projects/UI_UX/sports_app/5.png?raw=true"],
    category: ['ui/ux'],
    video: "/assets/movie.mp4",
    description: "FitnessBPM, an innovative solo project, is a highly gamified application that transforms fitness tracking into an engaging experience. Using a smart ring or watch, it tracks the user's beats per minute (BPM) and converts this data into experience points (EXP) within the app. The design, developed through extensive background research, includes setting various fitness goals and providing personalized challenges and suggestions. Its gamifying elements are chosen for their effectiveness in motivating and engaging users, while also promoting group activities. The app features levels, challenges, achievements, and badges to reward progress and encourage continued use. Creating FitnessBPM was an enjoyable journey; I crafted interactive designs using Figma, conducted UX testing on the prototype, and made iterative improvements based on user feedback. This project showcases my commitment to combining fitness with fun and community through thoughtful and user-centric design.",
    tags:["Wireframing","Product Design","Interaction Design"],
    features:["Gamified sports app","Smart device integration","Promoting healthy lifestyle"],
    demoURL:"https://www.figma.com/proto/vM5s9GExMRFpzVYZAuMsd7/Innovation-course-WIreframes?page-id=0%3A1&type=design&node-id=1-4&viewport=547%2C-77%2C0.94&t=jsuyFro2DdxFAzsL-1&scaling=scale-down&starting-point-node-id=1%3A96&mode=design"
  },

];

export const projectsNav = [
  {
    name: "featured",
  },
  {
    name: 'UI/UX',
  },
  {
    name: "Web",
  },
  {
    name: "app",
  },
  {
    name: "other",
  },
  {
    name: "all",
  }
];

